#! /bin/bash

# build a movie out of a set of images contained in a given 
# directory.

images_path="./images"

ffmpeg -framerate 15 \
	-i ./images/step-%06d.png \
	-vf scale=800:-1 \
	-c:v libx264 \
	-pix_fmt yuv420p \
	out.mp4

exit

# vim: ts=4 sw=4 et
